FROM nvidia/cudagl:11.4.2-base-ubuntu20.04
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Minimal setup
RUN apt update \
 && apt install -y locales lsb-release \
 software-properties-common
RUN add-apt-repository universe
RUN dpkg-reconfigure locales
 
# Install ROS Galactic
RUN apt update && apt install -y curl gnupg
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN sh -c 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null'
RUN apt update 
RUN apt-get install -y --no-install-recommends ros-galactic-desktop
RUN apt-get install -y --no-install-recommends python3-rosdep
RUN rosdep init \
 && rosdep fix-permissions \
 && rosdep update
RUN echo "source /opt/ros/galactic/setup.bash" >> ~/.bashrc